### ISSUE TITLE
InvalidValueError: setPosition: not a LatLng or LatLngLiteral: in property lat: not a number

### ISSUE THREAD

**Issue by wahiche** [Akryum/vue-googlemaps#10]
This was working when I first added everything and then all of a sudden it does not work any more.

The only error I get is this one:

InvalidValueError: setPosition: not a LatLng or LatLngLiteral: in property lat: not a number

I tried to parseFloat the value, I copied exactly what you had in the sample simple map and it did not work.  What is going on?

**Comment by Akryum** [comment]
Do you have a reproduction to share?

**Comment by wahiche** [comment]
I have just removed it all and will start again from scratch in hopes to not have the issue occur again.  I will reach out to you later tonight or tomorrow if things are still broken.  I want to hope it is user error and not issues with the plugin.  BTW excellent work on the plugin.

**Comment by wahiche** [comment]
Here is a code pen that shows what I have setup in my page(component) for the maps.

https://codepen.io/wahiche/pen/VrbrqQ

**Comment by wahiche** [comment]
Just wanted to let you know I have everything working again, not really sure what happened, but most likely something I did not do correctly.
