### ISSUE TITLE
Is there slot for marker?

### ISSUE THREAD

**Issue by diamond122** [Akryum/vue-googlemaps#108]
I want to customize markers.
It has two lines of text and each line has different style.
And the two lines are wrapped with in a white box with border-radius: 4.
How can I achieve this?

**Comment by beljand** [comment]
@AntonioCollin-s use https://github.com/eregnier/vue2-gmap-custom-marker

**Comment by diamond122** [comment]
@beljand Thank you. That's what I was looking for.
