### ISSUE TITLE
How to set the custom icon for the marker?

### ISSUE THREAD

**Issue by hjujah** [Akryum/vue-googlemaps#12]
Please is there a way to set a custom icon for the map marker?

**Comment by Akryum** [comment]
Use a icon font.

```html
<googlemaps-marker
  :label="{
    color: 'black',
    fontFamily: 'Material Icons',
    fontSize: '20px',
    text: 'face',
  }"
/>
```

**Comment by hjujah** [comment]
Ok, tnx for the answer, but I was more thinking about the image icon (png, jpg, etc...).
Anyway i figured it out...
I added the code bellow to the marker data.
```
icon: {
    url : "/static/logo.png",
    scaledSize: new google.maps.Size(150, 35)
}
```

and then this into the marker definition...
`:icon="marker.icon"`

**Comment by thanhthaohoang** [comment]
Hi ! 

@hjujah  I tried your solution and it works well but when I refresh my page, I got an error

`google is not defined`

**Comment by shredding** [comment]
@hjujah can you post the full code ... where did you add that data?

**Comment by ricardovigatti** [comment]
@shredding m just like this:

    <googlemaps-marker :icon="{ url: 'your-icon-url') }">
 
    </googlemaps-marker>
