### ISSUE TITLE
Can Markers support InfoWindow?

### ISSUE THREAD

**Issue by jcartwright** [Akryum/vue-googlemaps#16]
I've attempted to add content when rendering the Marker components, but the "slot" content seems to just be ignored.
```
<googlemaps-marker
  :key="..."
  :title="..."
  :position="..."
>
  <div>Info Window</div>
</googlemaps-marker>
```
I see comments in the code about supporting the `infowindow` inside a Marker, but it doesn't seem to work as I would expect.
```
render (h) {
  if (!this.$slots.default || this.$slots.default.length === 0) {
    return ''
  } else if (this.$slots.default.length === 1) {
    // So that infowindows can have a marker parent
    return this.$slots.default[0]
  } else {
    return h(
      'div',
      this.$slots.default
    )
  }
},
```

Am I missing something? Thanks for the work you're doing!

**Comment by walkerdigital** [comment]
+1

**Comment by murilolopes** [comment]
any news?

**Comment by maciz84** [comment]
Is there any workaround for now?

**Comment by ricardovigatti** [comment]
I'll try to make this works. But first, give me some background info here. 

This infoWindow feature it's implemented already or no? If it's implemented but not working, I can dig to find the issue. If not implemented yet, I can try to implement it, for this I need to know how this package is managing the current marker selected?

**Comment by jcartwright** [comment]
I was able to get the solution @Oscarato provided to work!

**Comment by nstcactus** [comment]
Unfortunately @Oscarato's approach won't work if you want to display a Vue component in the InfoWindow. Anyone has an idea on how to fix the lib?

**Comment by anteriovieira** [comment]
Try

```js
import Vue from 'vue'
import MyVueComponent from './MyVueComponent.vue'

export default {
    // ...
    selectMarker (refId) {
      const Wrapper= Vue.extend(MyVueComponent)
      const InfoMarker = new Wrapper().$mount()

      const map = this.$refs.map.$_map
      const marker = this.$refs[refId][0].$_marker
      const infowindow = new window.google.maps.InfoWindow({
        content: InfoMarker.$el
      })
      infowindow.open(marker, mark)
    }
}
```

Example:
![image](https://user-images.githubusercontent.com/1490347/73025408-4cf7e480-3e0e-11ea-8302-3fa41d1089b6.png)
