### ISSUE TITLE
Can't drag and drop map correctly, marker moves with drag direction

### ISSUE THREAD

**Issue by Radiergummi** [Akryum/vue-googlemaps#19]
This issue occurs on the demo page as well (using Chrome/MacOS): If you try to scroll the map by using drag and drop, it only moves by a very small distance, then sticking until you drag and drop again. As this is a little hard to put into words, I've made a GIF:

![feb -15-2018 13-05-01](https://user-images.githubusercontent.com/6115429/36255852-e02fe2e8-1250-11e8-9cdf-956ab47a8fa7.gif)

In my own case, the marker seems to move *with* the map if I drag and drop:
![feb -15-2018 13-07-24](https://user-images.githubusercontent.com/6115429/36255955-439a792e-1251-11e8-93fe-6eef048469d7.gif)

maps.google.com works fine, as other embedded maps (without this Vue component) do.
Any idea what causes this and how to resolve it?

**Comment by Radiergummi** [comment]
Okay, I feel a little stupid concerning the moving marker, obviously I was using the same coordinates object for the center prop and my marker position. Duh, rookie error.  

Cannot get rid of the drag and drop problem, though...

**Comment by uskithub** [comment]
Though I do not know how to fix it, it seems to be caused by binding an event handler to the update of the center property below.
https://github.com/Akryum/vue-googlemaps/blob/master/src/components/Map.vue#L131

**Comment by krishnateja12345** [comment]
Now whats the solution for dragging map cm by cm?
