### ISSUE TITLE
How to set `right click prop` option on Map? 

### ISSUE THREAD

**Issue by thearabbit** [Akryum/vue-googlemaps#2]
I would like to set  `right click prop` option on Map.
Please help me.
```js
<googlemaps-map id="map" :center.sync="center" :zoom.sync="zoom">
</googlemaps-map>
```
![image](https://user-images.githubusercontent.com/4495160/30902955-62a2d290-a397-11e7-8070-f0ae87d5570f.png)

**Comment by Akryum** [comment]
What do you mean?

**Comment by thearabbit** [comment]
I would like to use `right click` to `check destination of place` on my Map

**Comment by Akryum** [comment]
Well, you can listen to the `rightclick` event on the map and create a context menu (check on Google).

**Comment by thearabbit** [comment]
Oh, It doesn't default props for this.

**Comment by thearabbit** [comment]
Could you example?
