### ISSUE TITLE
The marker is not generated

### ISSUE THREAD

**Issue by AngelWayfarer** [Akryum/vue-googlemaps#3]
Hi I tried to use your plugin in a basic way: basic map and one marker with icon.
But I have some problems. The marker is visible in the VueDevtools, but not on the page... I tried both with icon and without it.. 
I use nuxt.js, but I have already tried both server-side an client-side render, but I had no success.. :-(
The map is working, but not the marker.

It is my code..
```!html
<div class="contacts__map">
	<googlemaps-map class="map"	:center="{lat: -25.363, lng: 131.044}" :zoom="17">
		<googlemaps-marker :position="{lat: -25.363, lng: 131.044}"></googlemaps-marker>
	</googlemaps-map>
</div>
````

and devtools
![image](https://user-images.githubusercontent.com/13068608/30962995-9b64c9fe-a454-11e7-8b8b-6fe65f9a1b30.png)

**Comment by TsooranKim** [comment]
me too...

**Comment by AngelWayfarer** [comment]
Thanks for the fixes
