### ISSUE TITLE
This page can't load Google Maps correctly.

### ISSUE THREAD

**Issue by fpilee** [Akryum/vue-googlemaps#31]
![2018-09-17 21_07_32-window](https://user-images.githubusercontent.com/1960075/45656794-bb5fc080-babd-11e8-9139-42467456621a.png)

Hey, 
I saw this in the demo page. The other library have the same error. I will have the same error in my app?

**Comment by devWaleed** [comment]
@fpilee There is an issue with your key. Google has updated some settings and this problem is reported by a lots of users on their apps. 

In short this doesn't have anything to do with the package.

**Comment by ricardovigatti** [comment]
@fpilee , did you fixed it?
