### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by bschulz87** [Akryum/vue-googlemaps#5]
Does not work in IE 11 V. 11.0.9600.18792

"Object doesn't support property or method 'assign'" in console when trying to view the demo.

**Comment by Akryum** [comment]
You need to polyfill ES2015 features like `Object.assign` in old browsers like Internet Explorer 11. [MDN polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) or [babel-polyfill](https://babeljs.io/docs/usage/polyfill/).
