### ISSUE TITLE
Using with Nuxt.js

### ISSUE THREAD

**Issue by homerjam** [Akryum/vue-googlemaps#7]
I'm having an issue using this component with Nuxt.js, I wonder if you have any ideas?

The map loads blank and as soon as I attempt to interact I get the following error in the console:

```
Uncaught TypeError: Cannot read property 'x' of undefined
```

This is the stripped back test case I'm using (modified version of hello world example):

```html
// pages/index.vue

<script>
import Vue from 'vue'
import 'vue-googlemaps/dist/vue-googlemaps.css'
import VueGoogleMaps from 'vue-googlemaps'

Vue.use(VueGoogleMaps, {
  load: {
    apiKey: API_KEY,
    libraries: []
  }
})

export default {
  data () {
    return {
      center: { lat: 0, lng: 0 }
    }
  },
  methods: {
    ready () {
      this.$refs.map.resize()
    }
  }
}
</script>

<template>
  <div>
    <h1>Welcome!</h1>
    <nuxt-link to="/about">About page</nuxt-link>
    <googlemaps-map ref="map" :center="center" @ready="ready"></googlemaps-map>
  </div>
</template>

<style>
.vue-google-map {
  width: 500px;
  height: 400px;
}
</style>
```

I found a suggestion that the element may not be ready when the map is initialised so I added an arbitrary delay in the `googleMapsReady()` function but this didn't help either.

Another suggestion was to try calling `resize()` which you can see I've tried in this test, again no help.

Thanks in advance!

**Comment by Samuell1** [comment]
Why you have import and added all plugin logic in page? Create plugin in `plugins` folder and import it in nuxt.config

**Comment by homerjam** [comment]
Purely for example sake, it doesn't work using plugin method either

**Comment by Samuell1** [comment]
Try removing `libraries` empty array maybe thats why is there error

**Comment by Samuell1** [comment]
For me works on nuxtjs, try it agian without any additional code copy all things from example

**Comment by homerjam** [comment]
Ok try this: https://glitch.com/edit/#!/utopian-rabbit

**Comment by Samuell1** [comment]
@homerjam add `:zoom="10"` for map

**Comment by homerjam** [comment]
OMG 😊 

Awesome thanks @Samuell1 !

FWIW - there was a warning for missing `center` but not `zoom` so I think I assumed it was optional.

**Comment by homerjam** [comment]
Submitted #8
